"""Generate shell completion scripts directly from argparse actions."""

from __future__ import annotations


def option_strings(parser) -> list[str]:
    return sorted({option for action in parser._actions for option in action.option_strings})


def render(shell: str, parser) -> str:
    options = " ".join(option_strings(parser))
    if shell == "bash":
        return f'''# Generated by csaf-assess --completion bash
_csaf_assess() {{ COMPREPLY=( $(compgen -W "{options}" -- "${{COMP_WORDS[COMP_CWORD]}}") ); }}
complete -F _csaf_assess csaf-assess
complete -F _csaf_assess python3
'''
    if shell == "zsh":
        return f"""#compdef csaf-assess
# Generated by csaf-assess --completion zsh
_csaf_assess() {{ _arguments '*: :({options})' }}
compdef _csaf_assess csaf-assess
"""
    if shell == "powershell":
        quoted = ", ".join(repr(item) for item in option_strings(parser))
        return f"""# Generated by csaf-assess --completion powershell
Register-ArgumentCompleter -CommandName csaf-assess -ScriptBlock {{
  param($wordToComplete)
  @({quoted}) | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }}
}}
"""
    raise ValueError(f"Unsupported shell {shell!r}")
