"""Remediation guidance keyed by control ID."""

from __future__ import annotations

REMEDIATION = {
    "CSAF-AWS-IAM-001": "Enable a hardware or virtual MFA device on the root user and store it securely offline.",
    "CSAF-AWS-IAM-002": "Delete all root access keys; use IAM roles or federated identities for programmatic access.",
    "CSAF-AWS-IAM-003": "Stop using the root user for routine tasks; delegate to least-privilege IAM roles.",
    "CSAF-AWS-IAM-004": "Set an account password policy requiring length >= 14 with complexity and reuse prevention.",
    "CSAF-AWS-IAM-005": "Require MFA for every IAM user with console access; enforce with an MFA-conditional policy.",
    "CSAF-AWS-IAM-006": "Rotate active access keys on a schedule (<= 90 days) and remove keys that are no longer needed.",
    "CSAF-AWS-IAM-007": "Disable or delete passwords and access keys unused beyond the inactivity threshold.",
    "CSAF-AWS-IAM-008": "Replace Action:* / Resource:* grants with least-privilege, service-scoped policies.",
    "CSAF-AWS-IAM-009": "Create an IAM Access Analyzer analyzer at the account or organization level and triage findings.",
    "CSAF-AWS-IAM-010": "Remove privilege-escalation-enabling permissions from non-admin principals; add permission boundaries.",
    "CSAF-AWS-S3-001": "Enable all four account-level S3 Block Public Access settings.",
    "CSAF-AWS-S3-002": "Remove public bucket policies/ACLs and enable Block Public Access on affected buckets.",
    "CSAF-AWS-S3-003": "Enable default SSE-KMS or SSE-S3 encryption on every bucket.",
    "CSAF-AWS-S3-004": "Add a bucket policy statement denying requests where aws:SecureTransport is false.",
    "CSAF-AWS-EC2-001": "Set instance metadata options to HttpTokens=required to enforce IMDSv2.",
    "CSAF-AWS-EC2-002": "Enable EBS encryption by default in each region.",
    "CSAF-AWS-EC2-003": "Restrict security groups on public instances and remove admin-port exposure to 0.0.0.0/0.",
    "CSAF-AWS-NET-001": "Restrict security-group ingress for ports 22/3389 to known management CIDRs or a bastion.",
    "CSAF-AWS-NET-002": "Remove all inbound and outbound rules from every default security group.",
    "CSAF-AWS-NET-003": "Enable VPC flow logs to CloudWatch Logs or S3 for every VPC in scope.",
    "CSAF-AWS-LOG-001": "Create a multi-region CloudTrail trail that is enabled and logging.",
    "CSAF-AWS-LOG-002": "Enable log file validation on all CloudTrail trails.",
    "CSAF-AWS-LOG-003": "Configure CloudTrail to encrypt log files with a customer-managed KMS key.",
    "CSAF-AWS-LOG-004": "Enable AWS Config recording in each region with an appropriate delivery channel.",
    "CSAF-AWS-LOG-005": "Enable Amazon GuardDuty in every region and route findings to your SIEM.",
    "CSAF-AWS-KMS-001": "Enable automatic annual rotation on customer-managed symmetric KMS keys.",
    "CSAF-AWS-RDS-001": "Recreate or snapshot-restore RDS instances with storage encryption enabled.",
    "CSAF-AWS-RDS-002": "Set PubliclyAccessible=false and place RDS instances in private subnets.",
    "CSAF-AWS-OPS-001": "Document and periodically test a break-glass procedure for root and privileged access.",
    # --- Azure ---------------------------------------------------------------
    "CSAF-AZ-IAM-001": "Delete custom RBAC roles granting Actions:* at subscription scope; use built-in least-privilege roles.",
    "CSAF-AZ-IAM-002": "Reduce subscription Owner assignments to a small, named set; use PIM eligible assignments for the rest.",
    "CSAF-AZ-DEF-001": "Enable Microsoft Defender for Cloud Standard-tier plans for servers, storage, and SQL workloads.",
    "CSAF-AZ-DEF-002": "Configure a monitored security contact email in Defender for Cloud environment settings.",
    "CSAF-AZ-STO-001": "Set 'Secure transfer required' (supportsHttpsTrafficOnly) to Enabled on every storage account.",
    "CSAF-AZ-STO-002": "Set allowBlobPublicAccess to false on every storage account and remove public containers.",
    "CSAF-AZ-STO-003": "Set minimumTlsVersion to TLS1_2 (or newer) on every storage account.",
    "CSAF-AZ-STO-004": "Set the storage account network ACL default action to Deny and allow only required networks.",
    "CSAF-AZ-NET-001": "Restrict NSG inbound rules for ports 22/3389 to management CIDRs, Azure Bastion, or just-in-time access.",
    "CSAF-AZ-NET-002": "Enable Network Watcher in every region that hosts virtual networks.",
    "CSAF-AZ-VM-001": "Migrate VMs from unmanaged VHD blobs to managed disks.",
    "CSAF-AZ-LOG-001": "Create a subscription diagnostic setting exporting Administrative, Security, Policy, and Alert categories.",
    "CSAF-AZ-SQL-001": "Enable auditing on every Azure SQL server with retention to a storage account or Log Analytics.",
    "CSAF-AZ-SQL-002": "Disable public network access on Azure SQL servers and connect via private endpoints.",
    "CSAF-AZ-KV-001": "Enable soft delete and purge protection on every key vault.",
    "CSAF-AZ-OPS-001": "Document and periodically test a break-glass procedure for Global Administrator and Owner access.",
    # --- GCP -----------------------------------------------------------------
    "CSAF-GCP-IAM-001": "Replace owner/editor/admin bindings on service accounts with least-privilege predefined roles.",
    "CSAF-GCP-IAM-002": "Delete user-managed service-account keys; use workload identity or attached service accounts.",
    "CSAF-GCP-IAM-003": "Rotate user-managed service-account keys on a schedule (<= 90 days) or eliminate them entirely.",
    "CSAF-GCP-IAM-004": "Replace basic owner/editor grants on users and groups with predefined least-privilege roles.",
    "CSAF-GCP-LOG-001": "Configure the project audit config to log ADMIN_READ, DATA_READ, and DATA_WRITE for allServices.",
    "CSAF-GCP-LOG-002": "Create an enabled, unfiltered log sink exporting all entries to a secured destination.",
    "CSAF-GCP-STO-001": "Remove allUsers/allAuthenticatedUsers bindings from bucket IAM policies and enable public access prevention.",
    "CSAF-GCP-STO-002": "Enable uniform bucket-level access on every bucket to disable legacy object ACLs.",
    "CSAF-GCP-NET-001": "Delete the auto-created 'default' network and define purpose-built VPCs with explicit firewall rules.",
    "CSAF-GCP-NET-002": "Restrict 0.0.0.0/0 ingress firewall rules for ports 22/3389 to IAP ranges or management CIDRs.",
    "CSAF-GCP-NET-003": "Enable flow logs on every standard VPC subnetwork.",
    "CSAF-GCP-VM-001": "Attach purpose-built least-privilege service accounts to instances instead of the default compute SA.",
    "CSAF-GCP-VM-002": "Remove external IPs from instances; use IAP, Cloud NAT, or load balancers for required connectivity.",
    "CSAF-GCP-VM-003": "Set enable-oslogin=TRUE in project metadata and remove instance-level overrides.",
    "CSAF-GCP-VM-004": "Remove serial-port-enable=true metadata from all instances.",
    "CSAF-GCP-KMS-001": "Set a rotation period of 90 days or less with a next-rotation time on symmetric CMEK keys.",
    "CSAF-GCP-SQL-001": "Remove 0.0.0.0/0 authorized networks from Cloud SQL; use private IP or the Cloud SQL Auth Proxy.",
    "CSAF-GCP-SQL-002": "Require TLS on public-IP Cloud SQL instances (sslMode ENCRYPTED_ONLY or stricter).",
    "CSAF-GCP-OPS-001": "Document and periodically test a break-glass procedure for organization and project owner access.",
}


def remediation_for(control_id: str) -> str:
    return REMEDIATION.get(control_id, "Review the control expectation and align the configuration accordingly.")
