# Generated by csaf-assess --completion bash
_csaf_assess() { COMPREPLY=( $(compgen -W "--accounts --allow-secret-discovery --attest-key-file --aws-profile --baseline --catalog --check-only --cleanup-tutorial --cloud --color --completion --engagement --engagement-key-file --explain --export --guide --help --kube-context --kubeconfig --live --log-level --max-workers --no-color --open-report --output-dir --output-format --plan --preflight --previous-findings --profile --project --projects --regions --self-check --skip-live-preflight --start --subscription --subscriptions --tutorial --version -h" -- "${COMP_WORDS[COMP_CWORD]}") ); }
complete -F _csaf_assess csaf-assess
complete -F _csaf_assess python3
