# Generated by csaf-assess --completion powershell
Register-ArgumentCompleter -CommandName csaf-assess -ScriptBlock {
  param($wordToComplete)
  @('--accounts', '--allow-secret-discovery', '--attest-key-file', '--aws-profile', '--baseline', '--catalog', '--check-only', '--cleanup-tutorial', '--cloud', '--color', '--completion', '--engagement', '--engagement-key-file', '--explain', '--export', '--guide', '--help', '--kube-context', '--kubeconfig', '--live', '--log-level', '--max-workers', '--no-color', '--open-report', '--output-dir', '--output-format', '--plan', '--preflight', '--previous-findings', '--profile', '--project', '--projects', '--regions', '--self-check', '--skip-live-preflight', '--start', '--subscription', '--subscriptions', '--tutorial', '--version', '-h') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
}
