# Generated by csaf-assess --completion bash
_csaf_assess() { COMPREPLY=( $(compgen -W "--attest-key-file --aws-profile --baseline --catalog --check-only --cleanup-tutorial --cloud --color --completion --engagement --engagement-key-file --explain --export --help --kube-context --kubeconfig --log-level --max-workers --no-color --output-dir --output-format --plan --preflight --previous-findings --profile --project --regions --self-check --subscription --tutorial --version -h" -- "${COMP_WORDS[COMP_CWORD]}") ); }
complete -F _csaf_assess csaf-assess
complete -F _csaf_assess python3
